services:
  - type: web
    name: portfolio-qa
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: main
    plan: free
    envVars:
      - key: APP_NAME
        value: "Portfolio QA DevOps"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        value: ""
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: MAIL_MAILER
        value: log
